<style type="text/css">
abbr {
	text-decoration: underline;
	cursor: help;
}

.preview-area-wrapper {
	width: auto;
	height: auto;
	position: relative;
}
</style>
<div class="yui3-u-1-3">
	<div class="sidebar-content">
		<div class="module">
			<h2></h2>
			<div class="module-content">
				<!-- Widget Start -->
				<div class="widget-template-preview-area">
				</div>
				<!-- Widget End -->
			</div>
		</div>
	</div>
</div>
