<style type="text/css">
abbr {
	text-decoration: underline;
	cursor: help;
}

.preview-area-wrapper {
	width: auto;
	height: auto;
	position: relative;
}

#hl-outer {
	background-color: #F09;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 13px;
	text-align: center;
	display: block;
	position: relative;
	width: 100%;
	height: 100%;
}
#hl-page {
	background: white;
	margin: 0px auto;
	text-align: left;
	display: block;
	position: relative;
	width: 214px;
	padding: 24px;
	height: 100%;
}
#hl-page-main {
	display: block;
}
#hl-left-main {
	display: block;
}
#left-rail {
}
#left-rail .inner {
	width: 184px;
}
.hl-std-left, .hl-std-right {
	border-bottom: 6px solid #F09;
	margin-bottom: 20px;
}
.hl-std-left .widgettitle, .hl-std-right .widgettitle {
	display: none;
}
.hl-std-left .widgettitle h2 {
	font-size: 30px;
	margin-bottom: 6px;
}
#hl-outer .textwidget {

}
#hl-outer .left {
	float: left;
}
.hl-hed-left, .hl-media-left {
	margin: 18px 0px 10px 24px;
}
#hl-outer a {
	font-weight: bold;
	color: #F09;
	text-decoration: none;
}
.gap-fix {
	vertical-align: bottom;
}
#hl-outer img {
	border: 0px;
}
.hl-content-left ul, .hl-std-right ul, .inner ul {
	list-style: none;
}
#left-rail .inner .last {
	border-bottom: 0px;
}
#hl-outer p {
	display: block;
}
.hl-tease-cont {width: 427px; margin-left:-110px; margin-top:10px;}
.hl-logo-tease-l {width: 427px; background:#fff;}
.hl-lteaser-cont {width: 142px;}
.hl-logo-tease-r {width: 140px;}
.hl-lteaser {margin-left: 10px}
.hl-lteaser img {margin-bottom: 4px; display: block;}
/* the logo teaser headlines */
.hl-tease-cont h2 {font-size: 12px; font-weight: bold;}
.hl-tease-cont h2 a{color:#000 !important; text-shadow:none !important; line-height:normal !important;}
</style>
<div id="hl-outer">
	<div id="hl-page">
		<div id="hl-page-main">
			<div id="hl-left-main" class="left">
				<div id="left-rail" class="left">
					<div class="inner">
						<div class="hl-std-left">
							<!-- Widget Start -->
							<div class="widget-template-preview-area">
							</div>
							<!-- Widget End -->
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
