<?php
/**
 * Enqueue static assets for Digital Daily feature.
 *
 * @package pmc-digital-daily
 */

namespace PMC\Digital_Daily;

use PMC;
use PMC_Ads;
use PMC\Global_Functions\Traits\Singleton;

/**
 * Class Assets.
 */
class Assets {
	use Singleton;

	/**
	 * Handle used to enqueue plugin's assets.
	 */
	public const ASSET_HANDLE = 'pmc-digital-daily';

	/**
	 * Priority at which assets are enqueued.
	 *
	 * Hooked later to ensure Google Analytics is already present.
	 */
	public const ENQUEUE_PRIORITY = 20;

	/**
	 * Asset data, loaded from the build script's output.
	 *
	 * @var array
	 */
	protected array $_asset_data;

	/**
	 * Assets constructor.
	 */
	protected function __construct() {
		$this->_setup_hooks();
	}

	/**
	 * Register hooks.
	 */
	protected function _setup_hooks(): void {
		add_action(
			'wp_enqueue_scripts',
			[
				$this,
				'enqueue_script',
			],
			static::ENQUEUE_PRIORITY
		);
	}

	/**
	 * Retrieve asset data generated by build script.
	 *
	 * Data is cached as `require_once` only returns the file contents on the
	 * first request, returning `true` thereafter.
	 *
	 * @return array
	 */
	protected function _get_asset_data(): array {
		if ( empty( $this->_asset_data ) ) {
			// `PMC::render_template` cannot be used as file returns an array.
			// Path is not dynamic.
			// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingCustomConstant
			$this->_asset_data = require_once BUILD_DIR_PATH
				. 'index.asset.php';
		}

		return $this->_asset_data;
	}

	/**
	 * Enqueue plugin script.
	 */
	public function enqueue_script(): void {
		if ( ! is_singular( POST_TYPE ) ) {
			return;
		}

		$asset_data = $this->_get_asset_data();

		// If `pmc-adm-v2` is active, leverage its IO polyfill.
		$pmc_io_handle = 'pmc-intersection-observer-polyfill';
		if ( wp_script_is( $pmc_io_handle, 'registered' ) ) {
			$asset_data['dependencies'][] = $pmc_io_handle;
		}

		// If `pmc-adm-v2` uses Boomerang, ensure it loads first.
		$boomerang_handle = 'pmc-async-adm-boomerang-script';
		if (
			$this->boomerang_is_available()
			&& wp_script_is( $boomerang_handle, 'enqueued' )
		) {
			$asset_data['dependencies'][] = $boomerang_handle;
		}

		wp_enqueue_script(
			static::ASSET_HANDLE,
			BUILD_DIR_URL . 'index.js',
			$asset_data['dependencies'],
			$asset_data['version'],
			false
		);

		wp_localize_script(
			static::ASSET_HANDLE,
			'pmcDigitalDailyConfig',
			[
				'coverAd'    => [
					'adDomSlug'      => 'coverwrap',
					'has'            => $this->boomerang_is_available()
						&& Meta::issue_has_cover_ad(
							get_queried_object_id()
						),
					'overlayId'      => 'pmc-digital-daily-cover-ad-overlay',
					'timeoutSeconds' => PMC::is_mobile() ? 20 : 10,
				],
				'isFullView' => Full_View::is(),
			]
		);
	}

	/**
	 * Condition certain features on the `pmc-adm-v2` Boomerang provider.
	 *
	 * @return bool
	 */
	public function boomerang_is_available(): bool {
		return false !== PMC_Ads::get_instance()->get_provider( 'boomerang' );
	}
}
